---

# This is an example of configuration to "run" sample algorithms w/ sample clients
# This sample main purpose to demonstrate wiring of the client and algorithms
# To run this "training" set algorithm/path to relaax algorithm location 'algorithms/sample'
# Start parameter server
# relaax-parameter-server --config sample.yaml
# Start RLX server
# relaax-rlx-server --config sample.yaml
# run client
# python client/sample_exchange.py

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: training/checkpoints/sample_app
  --log-level: DEBUG
  --metrics-dir: training/metrics/sample_app

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: DEBUG

agent:
  log_dir: logs/

# wsproxy:
#   --address: localhost:9000

algorithm:
  path: algorithms/sample

  action_size: 2                  # action size for the given environment
  state_size: [3]                 # array of dimensions for the input observation
  hidden_layers: [10, 20, 10]
  learning_rate: 1e-4
  rewards_gamma: 0.99             # rewards discount factor
  max_global_step: 1e8            # amount of maximum global steps to pass through the training
