environment:
  run: environment/start

relaax-parameter-server:
  --bind: localhost:7000
  --metrics-dir: logs/metrics/
  --checkpoint-dir: logs/checkpoints/
  --log-level: DEBUG

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: DEBUG

relaax-wsproxy:
  --bind: localhost:9000
  --log-level: DEBUG

algorithm:
  name: policy_gradient

  input:
    shape: [0]
    history: 1
    use_convolutions: false

  output:
    continuous: false
    action_size: 4

  hidden_sizes: [10]
  batch_size: 10
  learning_rate: 0.01
  GAMMA: 0.97 # rewards discount factor
