algorithm:
  name: da3c

  input:
    shape: [4]
    history: 1
    use_convolutions: false

  output:
    continuous: false
    action_size: 2                # action size for the given environment

  hidden_sizes: []
  batch_size: 5                   # local loop size for one episode

  use_lstm: false                 # to use LSTM instead of FF, set to the True
  max_global_step: 20000         # amount of maximum global steps to pass through the training

  initial_learning_rate: 0.02
  entropy_beta: 0.01              # entropy regularization constant
  rewards_gamma: 0.99             # rewards discount factor

  RMSProp:
    decay: 0.99
    epsilon: 0.1
  # gradients_norm_clipping: 40.0
