algorithm:
  name: da3c

  action_size: 2                  # action size for the given environment
  state_size: 4
  hidden_sizes: []
  history_len: 1                  # number of observations to stack in state
  episode_len: 5                  # local loop size for one episode
  batch_size: 800
  gpu: false                      # to use GPU, set to the True
  lstm: false                     # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  learning_rate: 1e-2
  entropy_beta: 1e-2              # entropy regularization constant
  GAMMA: 0.97             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
