---

# This is an example of configuration to "run" sample algorithms w/ sample clients
# This sample main purpose to demonstrate wiring of the client and algorithms
# To run this "training" set algorithm/path to relaax algorithm location 'algorithms/sample'
# Start parameter server
# relaax-parameter-server --config sample.yaml
# Start RLX server
# relaax-rlx-server --config sample.yaml
# run client
# python client/sample_exchange.py

environment:
  client: cartpole/main

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: training/checkpoints/sample_app
  --log-level: INFO
  --metrics-dir: training/metrics/sample_app

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: DEBUG

# wsproxy:
#   --address: localhost:9000

algorithm:
  path: ../algorithms/policy_gradient
  use_system_ps: false

  action_size: 2                  # action size for the given environment
  state_size: 4
  hidden_layers: [10]
  history_len: 1                  # number of observations to stack in state
  episode_len: 5                  # local loop size for one episode
  batch_size: 800
  gpu: false                      # to use GPU, set to the True
  lstm: false                     # to use LSTM instead of FF, set to the True
  max_global_step: 1e8            # amount of maximum global steps to pass through the training

  learning_rate: 1e-2             # 5e-5
  entropy_beta: 1e-2              # entropy regularization constant
  GAMMA: 0.99             # rewards discount factor
  RMSProp:
    decay: 0.99
    epsilon: 0.1
    gradient_norm_clipping: 40
