---

# This is an example of configuration to train TRPO-GAE with trpo test environment.
#
# To run this training navigate to empty directory next to relaax repo,
# open three terminals there and run:
# relaax-parameter-server --config ../relaax/config/trpo_test_env.yaml
# relaax-rlx-server --config ../relaax/config/trpo_test_env.yaml
# ../relaax/environments/Test_Envs/xpo_env

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: checkpoints/trpo_test
  --log-level: WARNING
  --metrics-dir: metrics_trpo_test

relaax-rlx-server:
  --bind: 0.0.0.0:7001
  --parameter-server: localhost:7000
  --log-level: WARNING

algorithm:
  path: ../relaax/algorithms/trpo_gae

  action_size: 4                  # action size for the given environment
  state_size: [4]                 # array of dimensions for the input observation
  hidden_layers_sizes: [64, 64]   # number of hidden units for MLP
  activation: tanh                # activation function for MLP
  use_filter: false               # use average filter of the incoming observations (and rewards)
  discrete: false                 # switch between continuous and discrete action spaces
  async: false                    # set to true to collect experience without blocking the updater

  PG_OPTIONS:
    timestep_limit: 200           # length in steps for one round in environment
    n_iter: 10000                 # number of updates to pass through the training (training length)
    timesteps_per_batch: 2000     # number of experience to collect before update
    rewards_gamma: 0.995          # rewards discount factor
    gae_lambda: 0.97              # lambda from generalized advantage estimation

  TRPO:
    cg_damping: 0.1               # multiple of the identity to Fisher matrix during CG
    max_kl: 0.01                  # KL divergence between old and new policy
