---

environment:
  run: python environment/training.py
  steps: 3000

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: logs/checkpoints
  --log-level: INFO
  --metrics-dir: logs/metrics

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: INFO

algorithm:
  name: policy_gradient

  input:
    shape: [16]
    history: 1
    use_convolutions: false

  output:
    continuous: false
    action_size: 4

  hidden_sizes: [64, 64]
  batch_size: 20
  learning_rate: 0.004
  GAMMA: 0.97 # rewards discount factor
