---

environment:
  client: environment/training.py

relaax-parameter-server:
  --bind: localhost:7000
  --checkpoint-dir: training/checkpoints/sample_app
  --log-level: INFO
  --metrics-dir: training/metrics/sample_app

relaax-rlx-server:
  --bind: localhost:7001
  --log-level: DEBUG

algorithm:
  path: ../../relaax/algorithms/policy_gradient

  action_size: 4 # action size for the given environment
  state_size: 0
  hidden_sizes: [10]
  batch_size: 10
  learning_rate: 1e-2
  GAMMA: 0.97 # rewards discount factor
